In [1]:
import pandas as pd
import numpy as np

In [2]:
trans = pd.read_csv('Transactions-Table 1.csv')

In [3]:
trans.head(3)

transaction_id  product_id  customer_id transaction_date online_order  \
0               1           2         2950          2/25/17        False   
1               2           3         3120          5/21/17         True   
2               3          37          402         10/16/17        False   

  order_status          brand product_line product_class product_size  \
0     Approved          Solex     Standard        medium       medium   
1     Approved  Trek Bicycles     Standard        medium        large   
2     Approved     OHM Cycles     Standard           low       medium   

   list_price standard_cost  product_first_sold_date  Unnamed: 13  \
0       71.49     US$ 53.62                  41245.0          NaN   
1     2091.47    US$ 388.92                  41701.0          NaN   
2     1793.43    US$ 248.82                  36361.0          NaN   

   Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN

In [4]:
tarns = trans.drop(columns=["transaction_id","Unnamed: 13","Unnamed: 14","Unnamed: 15","Unnamed: 16",
                           "Unnamed: 17"],inplace=True)

In [5]:
trans.isnull().sum()

product_id                   0
customer_id                  0
transaction_date             0
online_order               360
order_status                 0
brand                      197
product_line               197
product_class              197
product_size               197
list_price                   0
standard_cost              197
product_first_sold_date    197
dtype: int64

In [6]:
trans.online_order.unique()

array([False, True, nan], dtype=object)

In [7]:
trans['online_order'] = trans['online_order'].fillna(0)

In [8]:
trans.brand .unique()

array(['Solex', 'Trek Bicycles', 'OHM Cycles', 'Norco Bicycles',
       'Giant Bicycles', 'WeareA2B', nan], dtype=object)

In [9]:
trans['brand'] = trans['brand'].fillna(0)

In [10]:
trans.product_line.unique()

array(['Standard', 'Road', 'Mountain', 'Touring', nan], dtype=object)

In [11]:
trans['product_line'] = trans['product_line'].fillna(0)

In [12]:
trans.product_class.unique()

array(['medium', 'low', 'high', nan], dtype=object)

In [13]:
trans['product_class'] = trans['product_class'].fillna(0)

In [14]:
trans.product_size.unique()

array(['medium', 'large', 'small', nan], dtype=object)

In [15]:
trans['product_size'] = trans['product_size'].fillna(0)

In [16]:
trans['standard_cost'] = trans['standard_cost'].fillna(0)

In [17]:
trans['product_first_sold_date'] = trans['product_first_sold_date'].fillna(0)

In [18]:
#trans.isnull().sum()

In [19]:
trans.sort_values(by=['transaction_date'], inplace=True)

In [25]:
trans.tail(3)

product_id  customer_id transaction_date online_order order_status  \
6426          20         2249           9/9/17         True     Approved   
412           60          720           9/9/17        False     Approved   
1428          93         2667           9/9/17        False     Approved   

               brand product_line product_class product_size  list_price  \
6426   Trek Bicycles     Standard        medium        small     1775.81   
412   Giant Bicycles     Standard          high        small     1977.36   
1428        WeareA2B     Standard        medium       medium     1065.03   

     standard_cost  product_first_sold_date  
6426  US$ 1,580.47                  40303.0  
412   US$ 1,759.85                  41848.0  
1428    US$ 230.09                  41434.0

In [21]:
trans.product_id.unique()

array([ 87,  36,  85,  43,   3,  32,  78,   0,  74,  11,  59,   4,  50,
        35,  58,  94,  48,  27,  57,  77,  53,  18,  96,  24,  40,  63,
        28,  51,  46,  62,  17,  38,  67,  12,  19,  65,  64,  61,  22,
        71,  92,  89,  75,  60,  72,  52,  42,   5,   2,   9,  82,  39,
        37,  29,  34,  98,   7,  47, 100,  80,  33,  41,  20,  97,  15,
         1,  88,  21,  14,  90,  73,  10,  44,  84,  81,  68,  86,  66,
        54,  26,  83,  56,  31,  76,  95,   8,  79,  30,  23,  49,  91,
        13,   6,  16,  45,  99,  69,  93,  55,  70,  25])

In [22]:
#trans.to_csv('cleaned_trans.csv')

In [26]:
trans.online_order.unique()

array([False, True], dtype=object)

In [30]:
trans.loc[trans['online_order'] == True]

product_id  customer_id transaction_date online_order order_status  \
12484          85         2805           1/1/17         True     Approved   
16397          43         2160           1/1/17         True     Approved   
15137           3         1022           1/1/17         True     Approved   
18435           0         2011           1/1/17         True     Approved   
11995          59         1349           1/1/17         True     Approved   
...           ...          ...              ...          ...          ...   
487            10         1571           9/9/17         True     Approved   
17459          29         2036           9/9/17         True     Approved   
6520           82         3050           9/9/17         True     Approved   
4066           11         2240           9/9/17         True     Approved   
6426           20         2249           9/9/17         True     Approved   

                brand product_line product_class product_size  list_price  \
12484        WeareA2B     Standard        medium       medium     1228.07   
16397           Solex     Standard        medium       medium     1151.96   
15137   Trek Bicycles     Standard        medium        large     2091.47   
18435   Trek Bicycles         Road        medium       medium      290.62   
11995           Solex     Standard        medium        large     1061.56   
...               ...          ...           ...          ...         ...   
487          WeareA2B      Touring        medium       medium     1466.68   
17459  Norco Bicycles         Road        medium       medium      543.39   
6520   Giant Bicycles         Road        medium       medium     1538.99   
4066    Trek Bicycles     Standard        medium        small     1775.81   
6426    Trek Bicycles     Standard        medium        small     1775.81   

      standard_cost  product_first_sold_date  
12484    US$ 400.91                  36668.0  
16397    US$ 649.49                  41009.0  
15137    US$ 388.92                  36367.0  
18435    US$ 215.14                  42218.0  
11995    US$ 733.58                  34170.0  
...             ...                      ...  
487      US$ 363.25                  34586.0  
17459    US$ 407.54                  42696.0  
6520     US$ 829.65                  42404.0  
4066   US$ 1,580.47                  40303.0  
6426   US$ 1,580.47                  40303.0  

[9829 rows x 12 columns]

In [31]:
trans.loc[trans['online_order'] == False]

product_id  customer_id transaction_date online_order order_status  \
15204          87          123           1/1/17        False     Approved   
12543          36         3062           1/1/17        False     Approved   
19157          32          671           1/1/17        False     Approved   
12421          78         2552           1/1/17        False     Approved   
11281          74         3166           1/1/17        False     Approved   
...           ...          ...              ...          ...          ...   
14565           8         2846           9/9/17            0     Approved   
9931            2         1489           9/9/17        False     Approved   
17964           4          560           9/9/17        False     Approved   
412            60          720           9/9/17        False     Approved   
1428           93         2667           9/9/17        False     Approved   

                brand product_line product_class product_size  list_price  \
15204      OHM Cycles     Standard        medium       medium     1636.90   
12543           Solex     Standard           low       medium      945.04   
19157  Giant Bicycles     Standard        medium       medium      642.70   
12421  Giant Bicycles     Standard        medium        large     1765.30   
11281        WeareA2B     Standard        medium       medium     1228.07   
...               ...          ...           ...          ...         ...   
14565           Solex         Road        medium        small     1703.52   
9931            Solex     Standard        medium       medium       71.49   
17964  Giant Bicycles     Standard          high       medium     1129.13   
412    Giant Bicycles     Standard          high        small     1977.36   
1428         WeareA2B     Standard        medium       medium     1065.03   

      standard_cost  product_first_sold_date  
15204     US$ 44.71                  40410.0  
12543    US$ 507.58                  35052.0  
19157    US$ 211.37                  37337.0  
12421    US$ 709.48                  41533.0  
11281    US$ 400.91                  36668.0  
...             ...                      ...  
14565  US$ 1,516.13                  40649.0  
9931      US$ 53.62                  41245.0  
17964    US$ 677.48                  38573.0  
412    US$ 1,759.85                  41848.0  
1428     US$ 230.09                  41434.0  

[10171 rows x 12 columns]

In [32]:
trans.describe()

product_id   customer_id    list_price  product_first_sold_date
count  20000.00000  20000.000000  20000.000000             20000.000000
mean      45.36465   1738.246050   1107.829449             37823.508750
std       30.75359   1011.951046    582.825242              4734.747044
min        0.00000      1.000000     12.010000                 0.000000
25%       18.00000    857.750000    575.270000             35560.000000
50%       44.00000   1736.000000   1163.890000             38206.000000
75%       72.00000   2613.000000   1635.300000             40672.000000
max      100.00000   5034.000000   2091.470000             42710.000000

In [33]:
print(trans['brand'].where(trans['list_price'] < 1107.829449))

15204         NaN
12543       Solex
12484         NaN
16397         NaN
15137         NaN
           ...   
9931        Solex
17964         NaN
6426          NaN
412           NaN
1428     WeareA2B
Name: brand, Length: 20000, dtype: object


In [45]:
print(trans['product_line'].where(trans['list_price'] < 1107.829449 ))


15204         NaN
12543    Standard
12484         NaN
16397         NaN
15137         NaN
           ...   
9931     Standard
17964         NaN
6426          NaN
412           NaN
1428     Standard
Name: product_line, Length: 20000, dtype: object


In [46]:
print(trans['product_class'].where(trans['list_price'] == 2091.470000))



15204       NaN
12543       NaN
12484       NaN
16397       NaN
15137    medium
          ...  
9931        NaN
17964       NaN
6426        NaN
412         NaN
1428        NaN
Name: product_class, Length: 20000, dtype: object


In [41]:
Top_5 = trans.groupby("brand").list_price.sum().nlargest(n =5)
Top_5

brand
Solex             4496577.63
WeareA2B          4163083.61
Giant Bicycles    4091668.66
Trek Bicycles     3539512.36
OHM Cycles        2993420.35
Name: list_price, dtype: float64

In [42]:
bottom_5 = trans.groupby("brand").list_price.sum().nsmallest(n =5)
bottom_5

brand
0                  214907.24
Norco Bicycles    2657419.13
OHM Cycles        2993420.35
Trek Bicycles     3539512.36
Giant Bicycles    4091668.66
Name: list_price, dtype: float64